DROP TABLE IF EXISTS `player`;
CREATE TABLE IF NOT EXISTS `players` (
	`ckey` VARCHAR(32) NOT NULL,
	`ip` INT(10) UNSIGNED NOT NULL,
	`compid` VARCHAR(32) NOT NULL,
	`lastmode` VARCHAR(32) NOT NULL DEFAULT 'none',
	`ua` VARCHAR(256) NOT NULL DEFAULT 'none',
	`byond_major` SMALLINT(3) NOT NULL DEFAULT '0',
	`byond_minor` SMALLINT(4) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ckey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `participation`;
CREATE TABLE IF NOT EXISTS `participation` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`mode` VARCHAR(32) NOT NULL,
	`seen` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `antag`;
CREATE TABLE IF NOT EXISTS `antag` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`role` VARCHAR(32) NOT NULL,
	`mode` VARCHAR(32) NOT NULL,
	`selected` SMALLINT(4) NOT NULL,
	`selectedTotal` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
