-- OpenGoon API SQL Schema v1 --

DROP TABLE IF EXISTS `player`;
CREATE TABLE IF NOT EXISTS `player` (
	`ckey` VARCHAR(32) NOT NULL,
	`ip` INT(10) UNSIGNED NOT NULL,
	`compid` VARCHAR(32) NOT NULL,
	`lastmode` VARCHAR(32) DEFAULT NULL,
	`ua` VARCHAR(256) DEFAULT NULL,
	`byond_major` SMALLINT(3) DEFAULT NULL,
	`byond_minor` SMALLINT(4) DEFAULT NULL,
	PRIMARY KEY (`ckey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `ip-history`;
CREATE TABLE IF NOT EXISTS `ip-history` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`ip` INT(10) NOT NULL,
	`count` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `ip-history`;
CREATE TABLE IF NOT EXISTS `ip-history` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`ip` INT(10) NOT NULL,
	`count` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `participation`;
CREATE TABLE IF NOT EXISTS `participation` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`mode` VARCHAR(32) NOT NULL,
	`seen` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `antag`;
CREATE TABLE IF NOT EXISTS `antag` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`role` VARCHAR(32) NOT NULL,
	`mode` VARCHAR(32) NOT NULL,
	`selected` SMALLINT(4) NOT NULL,
	`selected_total` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `gauntlet`;
CREATE TABLE IF NOT EXISTS `gauntlet` (
	`ckey` VARCHAR(32) NOT NULL,
	`amount` SMALLINT(4) NOT NULL,
	PRIMARY KEY (`ckey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `vpn_whitelist`;
CREATE TABLE IF NOT EXISTS `vpn_whitelist` (
	`ckey` VARCHAR(32) NOT NULL,
	`akey` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`ckey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `jobbans`;
CREATE TABLE IF NOT EXISTS `jobbans` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`role` VARCHAR(32) NOT NULL,
	`akey` VARCHAR(32) NOT NULL,
	`server` VARCHAR(32) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `bans`;
CREATE TABLE IF NOT EXISTS `bans` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`ckey` VARCHAR(32) NOT NULL,
	`ip` INT(10) NOT NULL,
	`comp_id` VARCHAR(32) NOT NULL,
	`reason` VARCHAR(256) NOT NULL,
	`oakey` VARCHAR(32) DEFAULT NULL,
	`akey` VARCHAR(32) NOT NULL,
	`timestamp` INT(8) NOT NULL,
	`previous` INT(11) NOT NULL DEFAULT '0',
	`chain` SMALLINT(3) NOT NULL DEFAULT '0',
	`server` VARCHAR(32) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
